# Generated by Django 5.2.17 on 2026-09-28 06:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('sales', '0002_orderline_quantity_quotation_delivery_terms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Boshqa')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('delivered', 'Yetkazildi'), ('read', "O'qildi"), ('replied', 'Javob berdi'), ('failed', 'Yuborilmadi')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sales.quotation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-created_at'],
            },
        ),
    ]
