# Generated by Django 5.2.17 on 2026-09-29 19:17

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_standardize_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quotationline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="quotationline",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="advance_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
