# Generated by Django 5.2.17 on 2026-09-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_orderline_quantity_alter_orderline_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdelivery',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationdelivery',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
