# Generated by Django 5.2.17 on 2026-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_quotationdelivery_message_quotationdelivery_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdelivery',
            name='sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
