# Generated by Django 5.2.17 on 2026-10-02 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_pricelist_uniq_catalog_price_list_number_and_more'),
        ('sales', '0011_payment_cancellation_reason_payment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='price_override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='price_source',
            field=models.CharField(choices=[('catalog', 'Mahsulot katalogi'), ('price_list', 'Price-list'), ('manual', "Qo'lda kiritilgan")], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='source_price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='catalog.pricelist'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='source_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
