# Generated by Django 5.2.17 on 2026-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercompany',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='telegram',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='customercompany',
            name='customer_type',
            field=models.CharField(choices=[('local', 'Mahalliy'), ('retail', 'Chakana'), ('export', 'Eksport'), ('dealer', 'Diler')], default='local', max_length=20),
        ),
    ]
