# Generated by Django 5.2.17 on 2026-09-30 06:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0004_standardize_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=254)),
                ('encrypted_password', models.TextField()),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('smtp_security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'Shifrlanmagan')], default='starttls', max_length=10)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('imap_security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'Shifrlanmagan')], default='ssl', max_length=10)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_accounts', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'email'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user', 'email'), name='uniq_user_mailbox_email')],
            },
        ),
    ]
