# Generated by Django 5.2.17 on 2026-09-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mailboxaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxaccount',
            name='imap_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailboxaccount',
            name='smtp_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
