# Generated by Django 5.2.17 on 2026-10-03

import apps.common.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=apps.common.images.OptimizedImageField(
                blank=True,
                upload_to=apps.common.images.unique_image_upload_to,
                validators=[apps.common.images.validate_image_upload],
            ),
        ),
    ]
