# Generated by Django 5.2.17 on 2026-10-07 19:24

import apps.common.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_messageattachment_file_telegramupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='telegram_avatar',
            field=apps.common.images.OptimizedImageField(blank=True, upload_to=apps.common.images.unique_image_upload_to, validators=[apps.common.images.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='conversation',
            name='telegram_avatar_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='telegram_avatar_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
