# Generated by Django 5.2.17 on 2026-10-07 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
        ('communications', '0003_conversation_telegram_avatar_and_more'),
        ('organizations', '0004_standardize_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.CharField(default='INBOX', max_length=255)),
                ('uid_validity', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_uid', models.PositiveBigIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['mailbox', 'folder'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='email_thread_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='accounts.mailboxaccount'),
        ),
        migrations.AddField(
            model_name='message',
            name='email_cc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='email_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='email_from',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='email_in_reply_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='email_references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='email_subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='email_to',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='imap_uid',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='imap_uid_validity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='accounts.mailboxaccount'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailbox', 'email_message_id'], name='communicati_mailbox_e60b87_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('mailbox', 'email_folder', 'imap_uid_validity', 'imap_uid'), name='uniq_imported_email_uid'),
        ),
        migrations.AddField(
            model_name='mailboxsyncstate',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='accounts.mailboxaccount'),
        ),
        migrations.AddField(
            model_name='mailboxsyncstate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='mailboxsyncstate',
            constraint=models.UniqueConstraint(fields=('mailbox', 'folder'), name='uniq_mailbox_sync_folder'),
        ),
    ]
