# Generated by Django 5.2.17 on 2026-10-08 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_internal_participants(apps, schema_editor):
    Conversation = apps.get_model('communications', 'Conversation')
    ConversationParticipant = apps.get_model('communications', 'ConversationParticipant')
    Membership = apps.get_model('organizations', 'Membership')
    for conversation in Conversation.objects.filter(channel='internal').iterator():
        user_ids = set(
            conversation.messages.exclude(sender_id=None).values_list('sender_id', flat=True)
        )
        if conversation.assigned_to_id:
            user_ids.add(conversation.assigned_to_id)
        active_user_ids = Membership.objects.filter(
            organization_id=conversation.organization_id,
            user_id__in=user_ids,
            is_active=True,
        ).values_list('user_id', flat=True)
        ConversationParticipant.objects.bulk_create(
            [
                ConversationParticipant(
                    organization_id=conversation.organization_id,
                    conversation_id=conversation.id,
                    user_id=user_id,
                )
                for user_id in active_user_ids
            ],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar'),
        ('communications', '0004_mailboxsyncstate_conversation_email_thread_key_and_more'),
        ('crm', '0006_activity_contact'),
        ('customers', '0005_contact_avatar'),
        ('organizations', '0004_standardize_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['conversation', 'user'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='internal_direct_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('organization', 'channel', 'internal_direct_key'), name='uniq_internal_direct_conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communications.conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['organization', 'user'], name='communicati_organiz_89be03_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uniq_conversation_participant'),
        ),
        migrations.RunPython(backfill_internal_participants, migrations.RunPython.noop),
    ]
