# Generated by Django 5.2.17 on 2026-09-26 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Jarayonda'), ('won', 'Yutildi'), ('lost', 'Yutqazildi')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], default='medium', max_length=10)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers.customercompany')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('call', "Qo'ng'iroq"), ('meeting', 'Uchrashuv'), ('email', 'Email'), ('task', 'Vazifa'), ('note', 'Izoh')], max_length=20)),
                ('subject', models.CharField(max_length=220)),
                ('details', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'ordering': ['completed_at', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(default='#64748b', max_length=7)),
                ('is_closed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.pipelinestage'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_pipeline_stage'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status'], name='crm_lead_organiz_0f244d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'assigned_to'], name='crm_lead_organiz_347d31_idx'),
        ),
    ]
