# Generated by Django 5.2.17 on 2026-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='business_direction',
            field=models.CharField(choices=[('knit_fabric', 'Trikotaj mato'), ('weaving', "To'quvchilik"), ('yarn', 'Ip-kalava'), ('sewing', 'Tikuvchilik va xizmatlar'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
