# Generated by Django 5.2.17 on 2026-09-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_standardize_currency'),
        ('customers', '0003_customer_excel_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customercompany'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead'),
        ),
    ]
