# Generated by Django 5.2.17 on 2026-10-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_activity_customer_alter_activity_lead'),
        ('customers', '0003_customer_excel_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='customers.contact'),
        ),
    ]
