# Generated by Django 5.2.17 on 2026-09-28 06:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('stock', 'Omborda'), ('made_to_order', 'Buyurtma asosida'), ('stock_and_order', 'Ombor va buyurtma')], default='stock', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_basis',
            field=models.CharField(blank=True, default='FCA Koson', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_form',
            field=models.CharField(blank=True, choices=[('tube', 'Tub/yopiq'), ('open', 'Ochiq'), ('other', 'Boshqa')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, choices=[('raw', 'Xom'), ('pfd', "Bo'yashga tayyor (PFD)"), ('dyed', "Bo'yalgan")], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='knitting_machine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='price_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='yarn_count',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
