# Generated by Django 5.2.17 on 2026-09-28 07:00

import apps.common.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_availability_product_delivery_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=apps.common.images.OptimizedImageField(blank=True, upload_to=apps.common.images.unique_image_upload_to, validators=[apps.common.images.validate_image_upload]),
        ),
    ]
