# Generated by Django 5.2.17 on 2026-09-28 11:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('knitted_fabric', 'Trikotaj mato'), ('woven_fabric', "To'quv mato"), ('yarn', 'Ip-kalava'), ('apparel', 'Tayyor kiyim'), ('other', 'Boshqa')], default='knitted_fabric', max_length=30),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('price_list', "Narxlar ro'yxati"), ('product_list', "Mahsulotlar ro'yxati")], default='price_list', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, choices=[('knitted_fabric', 'Trikotaj mato'), ('woven_fabric', "To'quv mato"), ('yarn', 'Ip-kalava'), ('apparel', 'Tayyor kiyim'), ('other', 'Boshqa')], max_length=30)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('incoterm', models.CharField(default='FCA', max_length=10)),
                ('delivery_place', models.CharField(default='Koson, UZB', max_length=100)),
                ('incoterms_version', models.CharField(default='2020', max_length=4)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('alternative_delivery_terms', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Ruscha'), ('en', 'Inglizcha')], default='ru', max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Amalda'), ('expired', 'Muddati tugagan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description_snapshot', models.TextField(blank=True)),
                ('available_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('pcs', 'Dona'), ('kg', 'Kilogram'), ('m', 'Metr')], max_length=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('planned_loading_date', models.DateField(blank=True, null=True)),
                ('minimum_order_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_lines', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WovenFabricSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composition', models.CharField(default='100% cotton', max_length=200)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gsm', models.PositiveIntegerField()),
                ('weave', models.CharField(blank=True, max_length=30)),
                ('warp_yarn', models.CharField(blank=True, max_length=100)),
                ('weft_yarn', models.CharField(blank=True, max_length=100)),
                ('selvedge', models.CharField(blank=True, choices=[('closed', 'Yopiq'), ('open', 'Ochiq'), ('other', 'Boshqa')], max_length=20)),
                ('warp_threads', models.PositiveIntegerField(blank=True, null=True)),
                ('weft_threads', models.PositiveIntegerField(blank=True, null=True)),
                ('roll_length_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roll_length_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('construction_notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='woven_specification', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YarnSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yarn_count', models.CharField(max_length=50)),
                ('composition', models.CharField(default='100% cotton', max_length=200)),
                ('spinning_method', models.CharField(choices=[('ring', 'Ring'), ('open_end', 'Open-end (OE)'), ('other', 'Boshqa')], default='ring', max_length=20)),
                ('preparation', models.CharField(choices=[('carded', 'Carded'), ('combed', 'Combed'), ('other', 'Boshqa')], default='carded', max_length=20)),
                ('is_compact', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yarn_specification', to='catalog.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'document_type', 'number'), name='uniq_catalog_price_list_number'),
        ),
    ]
