# Generated by Django 5.2.17 on 2026-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_category_pricelist_pricelistline_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='incoterms_version',
            field=models.CharField(blank=True, default='2020', max_length=4),
        ),
        migrations.AddConstraint(
            model_name='pricelistline',
            constraint=models.UniqueConstraint(fields=('organization', 'price_list', 'product'), name='uniq_catalog_price_list_product'),
        ),
    ]
