# Generated by Django 5.2.17 on 2026-10-02 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_standardize_currency'),
        ('organizations', '0004_standardize_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricelist',
            name='uniq_catalog_price_list_number',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'document_type', 'number', 'version'), name='uniq_catalog_price_list_version'),
        ),
    ]
