# Generated by Django 5.2.17 on 2026-09-29 05:37

import django.core.validators
from django.db import migrations, models

import apps.common.images


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="bank_account",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="organization",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_delivery_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_incoterm",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_payment_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="director_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="organization",
            name="document_footer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_sender_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_name",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=apps.common.images.OptimizedImageField(
                blank=True,
                upload_to=apps.common.images.unique_image_upload_to,
                validators=[apps.common.images.validate_image_upload],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="order_number_prefix",
            field=models.CharField(default="SO", max_length=12),
        ),
        migrations.AddField(
            model_name="organization",
            name="production_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="quotation_number_prefix",
            field=models.CharField(default="QT", max_length=12),
        ),
        migrations.AddField(
            model_name="organization",
            name="quotation_validity_days",
            field=models.PositiveSmallIntegerField(
                default=14,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="short_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="signature_image",
            field=apps.common.images.OptimizedImageField(
                blank=True,
                upload_to=apps.common.images.unique_image_upload_to,
                validators=[apps.common.images.validate_image_upload],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stamp_image",
            field=apps.common.images.OptimizedImageField(
                blank=True,
                upload_to=apps.common.images.unique_image_upload_to,
                validators=[apps.common.images.validate_image_upload],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="whatsapp_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
