# Generated by Django 5.2.17 on 2026-10-08 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_standardize_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.organizationrole'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('organization', 'Tashkilot va xodimlar'), ('customers', 'Mijozlar va kontaktlar'), ('leads', 'Leadlar'), ('tasks', 'Vazifalar'), ('catalog', 'Mahsulotlar'), ('sales', 'Savdo'), ('reports', 'Hisobotlar'), ('mailbox', 'Mijozlar xabarlari')], max_length=30)),
                ('action', models.CharField(choices=[('view', 'Ko‘rish'), ('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', 'O‘chirish')], max_length=20)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_entries', to='organizations.organizationrole')),
            ],
            options={
                'ordering': ['module', 'action'],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationrole',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_organization_role_name'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'module', 'action'), name='uniq_role_module_action'),
        ),
    ]
